//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 25 15:17:37 GMT-12:00 2017
//----------------------------------------------------
package Graphik.AnalisisDatos;

/**
 * CUP generated class containing symbol constants.
 */
public class sym {

    /* terminals */
    public static final int coma = 5;
    public static final int llaveFin = 10;
    public static final int llaveInicio = 9;
    public static final int corInicio = 7;
    public static final int cadena = 4;
    public static final int decimal = 2;
    public static final int EOF = 0;
    public static final int entero = 3;
    public static final int error = 1;
    public static final int corFin = 8;
    public static final int salto = 6;
}
