
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 09 17:36:29 GMT-12:00 2017
//----------------------------------------------------

package Graphik.Analisis;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int mul = 55;
  public static final int menos = 54;
  public static final int menor = 62;
  public static final int mod = 57;
  public static final int graphikar_funcion = 21;
  public static final int punto = 49;
  public static final int importar = 4;
  public static final int parenInicio = 41;
  public static final int aumento = 59;
  public static final int div = 56;
  public static final int dosPuntos = 50;
  public static final int mas = 53;
  public static final int cadena = 73;
  public static final int mientras = 35;
  public static final int hereda = 14;
  public static final int imprimir = 28;
  public static final int resDecimal = 6;
  public static final int llamar = 17;
  public static final int privado = 13;
  public static final int menorIgual = 65;
  public static final int sino = 30;
  public static final int procesar = 24;
  public static final int decimal = 71;
  public static final int terminar = 38;
  public static final int caso = 32;
  public static final int resCadena = 8;
  public static final int incluir_HK = 19;
  public static final int or = 67;
  public static final int resBool = 9;
  public static final int caracter = 75;
  public static final int nuevo = 15;
  public static final int datos = 22;
  public static final int inteFin = 46;
  public static final int mayorIgual = 64;
  public static final int bool = 74;
  public static final int seleccion = 31;
  public static final int dondeTodo = 27;
  public static final int protegido = 12;
  public static final int columna = 23;
  public static final int vacio = 10;
  public static final int and = 69;
  public static final int retornar = 16;
  public static final int mayor = 61;
  public static final int corInicio = 51;
  public static final int dondeCada = 26;
  public static final int xor = 68;
  public static final int llamarHK = 20;
  public static final int iden = 76;
  public static final int EOF = 0;
  public static final int inicio = 18;
  public static final int corFin = 52;
  public static final int noIgual = 66;
  public static final int publico = 11;
  public static final int puntoComa = 40;
  public static final int idenImportar = 39;
  public static final int resCaracter = 7;
  public static final int error = 1;
  public static final int parenFin = 42;
  public static final int continuar = 37;
  public static final int si = 29;
  public static final int entero = 72;
  public static final int als = 2;
  public static final int disminucion = 60;
  public static final int hacer = 36;
  public static final int defecto = 33;
  public static final int donde = 25;
  public static final int pot = 58;
  public static final int igualIgual = 63;
  public static final int llaveFin = 44;
  public static final int resEntero = 5;
  public static final int para = 34;
  public static final int coma = 47;
  public static final int inteInicio = 45;
  public static final int not = 70;
  public static final int igual = 48;
  public static final int var = 3;
  public static final int llaveInicio = 43;
}

