
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 02 19:25:32 GMT-12:00 2017
//----------------------------------------------------

package Haskell.Analisis;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int decc = 22;
  public static final int mul = 37;
  public static final int mod = 39;
  public static final int dosPuntos = 6;
  public static final int par = 31;
  public static final int llaveInicio = 4;
  public static final int asc = 32;
  public static final int coma = 8;
  public static final int igual = 7;
  public static final int calcular = 18;
  public static final int let = 19;
  public static final int succ = 21;
  public static final int menorIgual = 46;
  public static final int end = 16;
  public static final int sum = 27;
  public static final int si = 11;
  public static final int length = 34;
  public static final int iden = 15;
  public static final int llaveFin = 5;
  public static final int numero = 50;
  public static final int menos = 36;
  public static final int then = 12;
  public static final int max = 24;
  public static final int menor = 43;
  public static final int EOF = 0;
  public static final int noIgual = 47;
  public static final int mas = 35;
  public static final int mayorIgual = 45;
  public static final int revers = 29;
  public static final int error = 1;
  public static final int mayor = 42;
  public static final int parenInicio = 10;
  public static final int entero = 52;
  public static final int or = 48;
  public static final int pot = 40;
  public static final int indice = 26;
  public static final int ans = 20;
  public static final int sqrt = 41;
  public static final int product = 28;
  public static final int caso = 14;
  public static final int impr = 30;
  public static final int desc = 33;
  public static final int igualIgual = 44;
  public static final int and = 49;
  public static final int parenFin = 9;
  public static final int dolar = 17;
  public static final int concatenar = 25;
  public static final int div = 38;
  public static final int corInicio = 2;
  public static final int min = 23;
  public static final int cadena = 51;
  public static final int corFin = 3;
  public static final int sino = 13;
}

