//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 22 15:12:31 GMT-12:00 2017
//----------------------------------------------------
package Haskell.Analisis;

/**
 * CUP generated class containing symbol constants.
 */
public class sym {

    /* terminals */
    public static final int decc = 24;
    public static final int mul = 39;
    public static final int mod = 41;
    public static final int dosPuntos = 6;
    public static final int par = 33;
    public static final int llaveInicio = 4;
    public static final int asc = 34;
    public static final int coma = 8;
    public static final int igual = 7;
    public static final int calcular = 20;
    public static final int caracter = 55;
    public static final int let = 21;
    public static final int succ = 23;
    public static final int menorIgual = 48;
    public static final int end = 18;
    public static final int sum = 29;
    public static final int si = 13;
    public static final int length = 36;
    public static final int iden = 17;
    public static final int llaveFin = 5;
    public static final int numero = 52;
    public static final int menos = 38;
    public static final int then = 14;
    public static final int max = 26;
    public static final int menor = 45;
    public static final int EOF = 0;
    public static final int noIgual = 49;
    public static final int mas = 37;
    public static final int mayorIgual = 47;
    public static final int revers = 31;
    public static final int error = 1;
    public static final int mayor = 44;
    public static final int parenInicio = 10;
    public static final int entero = 54;
    public static final int or = 50;
    public static final int pot = 42;
    public static final int indice = 28;
    public static final int ans = 22;
    public static final int puntoComa = 12;
    public static final int sqrt = 43;
    public static final int product = 30;
    public static final int caso = 16;
    public static final int impr = 32;
    public static final int desc = 35;
    public static final int igualIgual = 46;
    public static final int and = 51;
    public static final int salto = 11;
    public static final int parenFin = 9;
    public static final int dolar = 19;
    public static final int concatenar = 27;
    public static final int div = 40;
    public static final int corInicio = 2;
    public static final int min = 25;
    public static final int cadena = 53;
    public static final int corFin = 3;
    public static final int sino = 15;
}
